### PR TITLE
added a Carousel

### PR DESCRIPTION
**Pull request by Jayaditya-Contributor**
Greetings @mathcodes 

I have added a carousel , using react slick package (docs :- https://react-slick.neostack.com/ ) 

I could not manipulate the carousel buttons for some reason, and at first I wanted to add a gradient border ,But after sometime I felt backgroud gradient is more good , Hope u dont mind 🙏.... 

I became rusty in CSS , I need to brush up a bit 
If you have any, please reccomend any good resource to learn tailwindcss  😊....

Thanks

### CODE REVIEW

**Comment by mathcodes** [comment]
I like the carousel, nice work. One thought I had is it kind of takes away from providing the contributors with the credits they deserve (only the first few will realistically by seen ...). BUT, let's merge and utilize this somewhere throughout the app as a reusable component, and I'll change the main contributors sections back to show all the devs. 

Great work, thanks for your input. 

@everyone There are LOTS more to grab that are as simple and fun as this, and with some GREAT DEVS putting in hard work while I and others continue to load more and more content, we are on the way to something incredible here. Would love to keep you on board!

-Jon (@mathcodes)

**Review by mathcodes — APPROVED** [review]
Nice Job @Jayaditya-Contributor! I will probably use it as a reusable component and change to table format to optimize credentials given to the contributors. I realize this was my request, and thank you. Looks great and will be a nice addition for several pages to come!

**Comment by mathcodes** [comment]
@Jayaditya-Contributor consider adding some responsiveness to this. For example: displaying 6 slides on lg and up, 3 or 4 on md, 2 on sm, and 1 on xs... (just throwing those out there, experiment if you feel like tackling this!

**Comment by Jayaditya-Contributor** [comment]
Sir, I honestly felt my contributions was NOT taking the project to the new heights ,and i felt my contributions were just bothering the new updates. so i took a step back...

**Comment by mathcodes** [comment]
I apologize for the delay in merging. If that's got anything to do with how you feel, disregard that... that's my fault. I've been tied up with other projects. But no pressure. This is a pretty laid back, learning atmosphere, so let me know if there is anything I can do do make you feel more at home... I'd be happy to work on a PR with you if you'd like... but again, no pressure. I appreciate all you done thus far!

**Comment by Jayaditya-Contributor** [comment]
As soon as I tackle my college assignments, I will surley make changes to the carousel as you requested , It would be helpful (If I may ask) providing a refrence on the design of the carousel and the look on various devices .

Thank U @mathcodes

**Pull request merged**
