### PR TITLE
I have added myself as contributor

### PR DESCRIPTION
**Pull request by Jayaditya-Contributor**
Hey @mathcodes  , I apologise for neglecting the guidlines, again thank u for the opportunity.

### CODE REVIEW

**Comment by Jayaditya-Contributor** [comment]
Screenshot 2023-01-26 162408

I dont understand this problem... it is showing the html but it is perfectly working in my 
html editor , this issue is happening in the readme file

Screenshot 2023-01-26 161952

**Review by mathcodes — APPROVED** [review]
I fixed the readme issue. All the anchor tags (<a>) weren't being closed (</a>). All good now 👍

**Comment by mathcodes** [comment]
@Jayaditya-Contributor No problem! Your input and contributions are much appreciated. Let me know if you have any more questions 👍

**Comment by Jayaditya-Contributor** [comment]
Greetings @mathcodes !

Recently I started learning React and Tailwindcss, So I used it to build a Demo Landing page for contentfordevelopers, I wanted to pull request but I am overwelmhed by the codebase , I have no idea on redux or sass, So I made an entirely new folder and made the landing page from scratch... I did not gave much attention to the footer....

Waiting for your feedback!!

Thank You

here is the link :-
https://63daa885798b480441cc0b29--whimsical-phoenix-c93208.netlify.app/

here is the Github repo :-
https://github.com/Jayaditya-Contributor/DemoContentForDevLanding

**Comment by mathcodes** [comment]
> Greetings @mathcodes !
> 
> Recently I started learning React and Tailwindcss, So I used it to build a Demo Landing page for contentfordevelopers, I wanted to pull request but I am overwelmhed by the codebase , I have no idea on redux or sass, So I made an entirely new folder and made the landing page from scratch... I did not gave much attention to the footer....
> 
> Waiting for your feedback!!
> 
> Thank You
> 
> here is the link :- https://63daa885798b480441cc0b29--whimsical-phoenix-c93208.netlify.app/
> 
> here is the Github repo :- https://github.com/Jayaditya-Contributor/DemoContentForDevLanding

Nice @Jayaditya-Contributor ,

I think this looks pretty good. I like the contributors in a carousel, nice touch. Here are some things I would change / consider when creating UIs:
- evenly space columns horizontally in footer
- fix your responsiveness around sm / md as the card element and the navbar are wider than the rest of the page/containers.
- stick with regular and consistently-shaped buttons
- keep titles the same size (this goes for all font/text)

Hope that helps! Nice job. Feel free to submit PRs moving forward. No pressure. Maybe you could implement that carousel into homepage like yours?

**Pull request merged**
