### PR TITLE
Clean up the code and include best practices

### PR DESCRIPTION
**Pull request by MONSEFOT**
@mathcodes ,  I  focused on the leetcode page and its related pages, I will continue working on other pages as well
these are the general changes that I've made to this branch, there were some bad practices in the code I tried to fix them all:

also the solutions of the problems in the `/data/` folder I will convert them to json based data files later.

- [x] remove useless imports
- [x] remove the `/pages/page.css` and convert the css margin to a tailwind one
- [x] rename the pages default exported function with the same name of the component (the names were `PageTemplate`)
- [x] clean up the leetcode page' code
- [x] inhance the `/data/images.js` way of export images (map instead of array)
- [x] rename the problemset table to `ProblemSetTable.jsx` and the components file to `ProblemSetTable/index.jsx`
- [x] remove unnecessary tailwind classes in the leetcode page & improve the conditioned tailwind classes
- [x] using json based data files other than js ones
- [x] make the scrolling behavior of the table auto
- [x] implement auto icons importing based on the icon names in the json datafile
- [x] build template page for leetcode ,hackerrank & codeforces  also I removed the repeated code
- [x] build a template page for all coding solutions and I put them in one data file

### CODE REVIEW

**Comment by MONSEFOT** [comment]
I found a lot of useless files and images and code I removed almost all of it, and about using images and videos it's better to put them all in a structured folder in the public direcroty and call them using a dyamic url call from the public the system will work on whatever the app url is:

the folder contains the png images is located in `public/assets/png`

for example if I had to include an image called _example.png_ I would do it this way:

```html
<img src="/assets/png/example.png" alt="" />
```

**Comment by MONSEFOT** [comment]
These are later tasks to do:

- [ ] build theme context instead of js script in the public directory

**Comment by MONSEFOT** [comment]
I found a lot of repeated code that could've been put in a template for example the leetcode , codeforces, hackerrank pages, those pages are the same template and it is just the data which changes here, so I built a template for them, also I put all the solutions of the coding problems in one datafile simply because they all have the same object structure, we could later change the id of solution to match the id of its problem whether the id is in the leetcode data file or other datafile.

Also I renamed almost all the pages and comonents to have an understandable names for the developers, because I had a hard time to understand every piece of component.

**Comment by MONSEFOT** [comment]
I hope you like my work and I actually like this project, it is a great if you successed building it @mathcodes

**Comment by mathcodes** [comment]
@MONSEFOT - This is a LOT of really great work 🔥

The only reason I'm not merging it is the links aren't working, or bringing me to the templates you created: 

Screenshot 2023-07-31 at 12 50 42 AM

What do you think about breaking this up into smaller PRs that build into your idea here. I love what you're doing and really appreciate your time and contributions. 

Let me know how you'd like to proceed to implement these changes.

**Comment by mathcodes** [comment]
@MONSEFOT - This is a LOT of really great work 🔥

The only reason I'm not merging it is the links aren't working, or bringing me to the templates you created: 

Screenshot 2023-07-31 at 12 50 42 AM

What do you think about breaking this up into smaller PRs that build into your idea here. I love what you're doing and really appreciate your time and contributions. 

Let me know how you'd like to proceed to implement these changes.

**Comment by MONSEFOT** [comment]
> @MONSEFOT - This is a LOT of really great work 🔥
> 
> The only reason I'm not merging it is the links aren't working, or bringing me to the templates you created:
> 
> Screenshot 2023-07-31 at 12 50 42 AM
> What do you think about breaking this up into smaller PRs that build into your idea here. I love what you're doing and really appreciate your time and contributions.
> 
> Let me know how you'd like to proceed to implement these changes.



> @MONSEFOT - This is a LOT of really great work 🔥
> 
> The only reason I'm not merging it is the links aren't working, or bringing me to the templates you created:
> 
> Screenshot 2023-07-31 at 12 50 42 AM
> What do you think about breaking this up into smaller PRs that build into your idea here. I love what you're doing and really appreciate your time and contributions.
> 
> Let me know how you'd like to proceed to implement these changes.

I 'll try to fix the problem of links, also I just made a change to clean the unnescessery code and I improved it to be flexible for change with a good architecture, the work starts after this change, using auto generated pages based on data keeps the site working and not craching when you decided to change to a database.

**Pull request closed without merging**
