### PR TITLE
[fix] create docs-style-guide.md

### LINKED ISSUE #166: Internal Docs Style Guide
Hey @mathcodes! :) Have you considered having a style guide for the Docs on this repo? It'd be a great way for contributors to gain tech writing skills! :)

### PR DESCRIPTION
**Pull request by CBID2**
## Issues
Fixes #166
## Changes Proposed 
This PR adds a style guide to the repository to ensure its documentation uses effective and inclusive communication. 
## Screenshots 
screenshot of docs guide

## Notes to Reviewers
Constructive feedback is greatly appreciated! 😄

### CODE REVIEW

**Comment by mathcodes** [comment]
Just curious, what did you base this off of? I think we can use it as a starting point, but it needs some more. How do you feel about using this guideline? If you don't have the time I can build off this and do it, but itd be great to get you on board!!!! (Also, please do the first contribution.... super easy: https://github.com/mathcodes/contentfordevelopers/blob/main/GUIDELINES.md#first_contribution)

OUTLINE:
Introduction

Purpose of the Style Guide
Target Audience
Overview of Open Source Documentation
Documentation Principles

Accuracy and Precision
Clarity and Simplicity
Consistency
Accessibility
Inclusivity
Writing Style

Use plain language
Write in a concise and clear manner
Avoid jargon and technical terms when possible
Use active voice and present tense
Organize content logically and coherently
Structure and Formatting

Document structure (Introduction, Installation, Usage, etc.)
Use headings and subheadings consistently
Employ bullet points and numbered lists for clarity
Utilize tables, diagrams, and screenshots where necessary
Use code blocks and syntax highlighting for code examples
Language and Grammar

Spelling and grammar guidelines
Use of inclusive language
Consistent use of terminology
Writing for translation and localization
Guidelines for non-native English speakers
API and Code Documentation

Documenting functions, classes, and methods
Parameter and return value descriptions
Code examples and usage patterns
Naming conventions and best practices
Integration with automated documentation tools
User Interface Documentation

Documenting user interfaces and workflows
Describing UI elements and their functions
Step-by-step instructions for common tasks
Visual representations of UI components
Troubleshooting and FAQs for user issues
Collaboration and Contribution Guidelines

Guidelines for contributors and maintainers
Version control and documentation updates
Documentation review process
Style and formatting conventions for contributions
Licensing and attribution requirements
Documentation Maintenance

Updating and archiving documentation
Tracking changes and versioning
User feedback and issue management
Documentation maintenance responsibilities
Continuous improvement and iteration
Additional Resources

Reference materials and external documentation
Recommended tools and software for documentation
Writing guides and resources
Open source documentation examples
Appendix:

Glossary of Terms
Style Guide Version History
Contributors and Acknowledgments

**Comment by CBID2** [comment]
Hi @mathcodes! I based it off things I have seen on errors I've seen in other docs. As far as the other parts, you can add some of the sections you created. To do it all would be overwhelming.

**Comment by mathcodes** [comment]
I want to merge it as a work in progress bu lets keep the issue up, raise it again.

**Comment by mathcodes** [comment]
I want to merge it as a work in progress bu lets keep the issue up, raise it again.

**Comment by CBID2** [comment]
> I want to merge it as a work in progress bu lets keep the issue up, raise it again.

Sure @mathcodes! :)

**Pull request merged**
